
[workspace]
resolver = "3"
members = ["laptop_server", "termux_server"]

[workspace.dependencies]

# Laptop server
serde ={ version = "1.0.228" , features = ["derive"]}
serde_json ={ version = "1.0.148"}

# Termux server
ctrlc ={ version = "*"}