[package]
name = "laptop_server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde ={ workspace = true}
serde_json ={ workspace = true}
egui = "0.33.0"
eframe ={ version = "0.33.0"}
egui_plot = "0.34.0"